language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

  before_install:
    - npm install -g codecov

  script:
    - npm test -- --coverage

  after_success:
    - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

sudo: required

