language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

  before_install:
    - npm install -g codecov

  script:
    - npm test -- --coverage

  after_success:
    - codecov --token=cea8f735-39f1-44ce-8294-d1d043320e2f

sudo: required

